# Repo-pinned Codex CLI config
# Mirrors the current local ~/.codex/config.toml at the time of publishing.
# Contains no credentials. Auth is provided separately via ~/.codex/auth.json.

model = "gpt-5"
model_reasoning_effort = "high"

approval_policy = "on-failure"
sandbox_mode = "workspace-write"
tools.web_search = true

[sandbox_workspace_write]
network_access = true
