train:
  horizon_days: 3
  label: excess_return
  fee_bps: 7
  slip_bps: 10
  atr_theta: 0.25
  walk_forward:
    folds: 5
    embargo_days: 3
  seed: 42
model:
  type: lgbm
  params:
    max_depth: 7
    n_estimators: 320
    learning_rate: 0.05
    subsample: 0.9
    colsample_bytree: 0.8
inference:
  p_gate: 0.65
  clamp:
    buy_budget_frac: [0.0, 0.3]
    bias: [-0.2, 0.2]
execution:
  fill_prob_target: 0.65
  slip_bps_cap: 40
schedule:
  intraday_score:
    - "09:16"
    - "11:25"
    - "13:05"
    - "14:25"
io:
  paths:
    snapshot: "out/snapshot.csv"
    metrics: "out/metrics.csv"
    sector_strength: "out/sector_strength.csv"
    session: "out/session_summary.csv"
    prices: "out/prices_history.csv"
    portfolio: "out/portfolio_clean.csv"
