data:
  prices: tests/fixtures/backtest/prices_ci.csv
  calendar: tests/fixtures/backtest/calendar_ci.csv
  watchlist: tests/fixtures/backtest/watchlist_ci.csv
config:
  initial_cash: 1000000
  seed: 17
  fees:
    commission_bps: 2
    tax_bps: 0
  liquidity_model:
    type: touch_full
  slippage_model:
    type: none
  horizon_eval_days: [1, 3]
  quality_gates:
    min_fill_rate: 0.0
    max_drawdown: 1.0
    min_trades: 0
  objective: sharpe
  watchlist:
    min_priority: 0.55
  buy_budget_frac: 0.1
  new_max: 2
  add_max: 1
  ttl_days: 2
  entry_price_offset_ticks: 1
  limit_safety_spread_ticks: 1
  lot_size: 100
engine:
  builder: backtest.sample_builder.sample_builder
