watchlist.min_priority:
  - 0.60
  - 0.65
  - 0.70
  - 0.75
buy_budget_frac:
  - 0.10
  - 0.15
  - 0.20
new_max:
  - 4
  - 6
  - 8
add_max:
  - 2
  - 3
  - 4
ttl_days:
  - 3
  - 5
  - 7
entry_price_offset_ticks:
  - 0
  - 1
  - 2
limit_safety_spread_ticks:
  - 1
  - 2
  - 3
