name: Data - Vietstock Fundamentals

on:
  schedule:
    # 10:20 UTC == 17:20 ICT
    - cron: '20 10 * * *'
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version'
        required: false
        default: '3.11'

concurrency:
  group: data-vietstock-fundamentals-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  collect:
    name: Collect Vietstock fundamentals
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ inputs.python-version || '3.11' }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version || '3.11' }}
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Chromium
        run: |
          set -euo pipefail
          python -m playwright install --with-deps chromium

      - name: Run collector
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          set -euo pipefail
          python scripts/data_fetching/run_data_jobs.py --job collect_vietstock_fundamentals

      - name: Upload artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: vietstock-fundamentals-${{ github.run_id }}
          if-no-files-found: warn
          retention-days: 7
          path: |
            data/fundamentals_vietstock.csv
            out/logs/data_jobs/**
