name: Test Suite

on:
  push:
    branches:
      - main
      - work
      - 'feature/**'
      - 'bugfix/**'
  pull_request:
  workflow_call:

jobs:
  tests:
    name: Run broker tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run broker test suite
        run: ./broker.sh tests

      # Backtest tuning smoke test removed to speed up CI; use the dedicated
      # 'Tuning Backtest Promote' workflow when needed.
