name: Test Suite

on:
  push:
    branches:
      - main
      - work
      - 'feature/**'
      - 'bugfix/**'
  pull_request:
  workflow_call:

jobs:
  tests:
    name: Run broker tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run broker test suite
        run: ./broker.sh tests

      - name: Run backtest tuning smoke test
        run: |
          python -m backtest.tune \
            --grid configs/tune_grid_ci.yaml \
            --base-config configs/replay_ci.yaml \
            --train-start 2024-01-01 --train-end 2024-01-04 \
            --val-start 2024-01-05 --val-end 2024-01-07 \
            --out backtest_out/ci_smoke \
            --top-k 1
