name: Tuning Nightly Calibrations

on:
  push:
    # Avoid infinite loops when the workflow commits its own outputs.
    paths-ignore:
      - 'config/policy_nightly_overrides.json'
      - 'config/policy_ai_overrides.json'
  workflow_dispatch:
  workflow_call:
    inputs:
      python-version:
        description: "Python version"
        required: false
        type: string
        default: "3.11"

concurrency:
  group: tuning-nightly-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  nightly_calibrations:
    name: Calibrate policy inputs overnight
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ inputs.python-version || '3.11' }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version || '3.11' }}
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare sample inputs
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p in/portfolio
          if [ -f samples/portfolio.csv ]; then
            cp -f samples/portfolio.csv in/portfolio/sample_portfolio.csv
          fi

      - name: Unified tune (AI + calibrators)
        run: |
          set -euo pipefail
          ./broker.sh tune

      - name: Persist unified overlay (commit and push)
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          set -euo pipefail
          test -f config/policy_overrides.json || { echo '::error::unified policy not found'; exit 2; }
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin "$BRANCH_NAME"
          git rebase "origin/$BRANCH_NAME" || { echo 'Rebase failed, trying to continue'; }
          git add config/policy_overrides.json
          git commit -m "chore(policy): update unified policy_overrides via tune" || echo "No changes to commit"
          for i in 1 2 3; do
            if git push origin "$BRANCH_NAME"; then exit 0; fi
            echo "Push failed, retry $i/3 after rebase"
            git fetch origin "$BRANCH_NAME"
            git rebase "origin/$BRANCH_NAME" || true
            sleep 2
          done
          echo "::error::Failed to push after retries"; exit 1

      - name: Upload artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: tuning-artifacts-unified
          path: |
            out/
            config/policy_overrides.json
            out/orders/policy_overrides.json
