name: Tuning AI Overrides

on:
  workflow_dispatch:
    inputs:
      rounds:
        description: "Number of Codex analysis rounds (1-3)"
        required: false
        default: "1"
      python-version:
        description: "Python version"
        required: false
        default: "3.11"
      node-version:
        description: "Node.js version for Codex CLI"
        required: false
        default: "20"
  schedule:
    # Note: GitHub cron uses UTC. Vietnam (ICT) = UTC+7, no DST.
    # Run every 2 hours to refresh AI overlays on a predictable cadence.
    - cron: '0 */2 * * *'
  workflow_call:
    inputs:
      rounds:
        description: "Number of Codex analysis rounds (1-3)"
        required: false
        type: string
        default: "1"
      python-version:
        description: "Python version"
        required: false
        type: string
        default: "3.11"
      node-version:
        description: "Node.js version for Codex CLI"
        required: false
        type: string
        default: "20"
    secrets:
      CODEX_AUTH_JSON:
        required: true

concurrency:
  group: tuning-ai-overrides-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  generate:
    name: Generate and persist policy_overrides.json via Codex CLI
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      BROKER_CX_GEN_ROUNDS: ${{ inputs.rounds || '1' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ inputs.python-version || '3.11' }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version || '3.11' }}
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Node ${{ inputs.node-version || '20' }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version || '20' }}

      - name: Install Codex CLI
        run: |
          set -euo pipefail
          npm install -g @openai/codex@latest
          codex --version

      - name: Configure Codex auth from secret
        env:
          CODEX_AUTH_JSON: ${{ secrets.CODEX_AUTH_JSON }}
        run: |
          set -euo pipefail
          mkdir -p "$HOME/.codex"
          if [ -z "${CODEX_AUTH_JSON:-}" ]; then
            echo "::error::Missing secret CODEX_AUTH_JSON"; exit 1; fi
          printf '%s' "$CODEX_AUTH_JSON" > "$HOME/.codex/auth.json"
          chmod 600 "$HOME/.codex/auth.json"

      - name: Install Codex config from repo
        run: |
          set -euo pipefail
          mkdir -p "$HOME/.codex"
          test -f .codex/config.toml || { echo '::error::.codex/config.toml not found in repo; aborting per fail-fast policy'; exit 2; }
          cp -f .codex/config.toml "$HOME/.codex/config.toml"
          chmod 600 "$HOME/.codex/config.toml"

      - name: Unified tune (AI + calibrators)
        run: |
          set -euo pipefail
          echo "Running unified tune, rounds=$BROKER_CX_GEN_ROUNDS"
          ./broker.sh tune

      - name: Persist unified overlay (commit and push)
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          set -euo pipefail
          test -f config/policy_overrides.json || { echo '::error::generated config/policy_overrides.json missing'; exit 2; }
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Ensure we are up-to-date before committing/pushing
          git fetch origin "$BRANCH_NAME"
          git rebase "origin/$BRANCH_NAME" || { echo 'Rebase failed, attempting to continue per fail-fast policy'; }
          git add config/policy_overrides.json
          git commit -m "chore(policy): update unified policy_overrides via tune" || echo "No changes to commit"
          # Push with small retry window in case of concurrent updates
          for i in 1 2 3; do
            if git push origin "$BRANCH_NAME"; then exit 0; fi
            echo "Push failed, retry $i/3 after rebase"
            git fetch origin "$BRANCH_NAME"
            git rebase "origin/$BRANCH_NAME" || true
            sleep 2
          done
          echo "::error::Failed to push after retries"; exit 1

      - name: Upload artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: policy-overrides-unified
          path: |
            config/policy_overrides.json
            out/debug/**
